Began asm parser ; Added lib ; Added Criterion unit tests ; Updated Makefiles ; Updated README.md

diff --git a/asm/Makefile b/asm/Makefile
--- a/asm/Makefile
+++ b/asm/Makefile
@@ -5,7 +5,10 @@
 ## Makefile
 ##
 
-SRC = 	main.c
+SRC = 	main.c \
+parser_check_syntax.c \
+parser_free.c \
+parser_linked_list.c
 
 OBJ =   $(SRC:.c=.o)
 
@@ -18,10 +21,11 @@ SANITIZE	=	-fsanitize=address,undefined \
 -fsanitize-recover=address,undefined
 ANALYZER	=
 
-INCLUDE = ../include/
+INCLUDE_DIR	= ../include/
+LIB_DIR	=	../lib/
 CFLAGS  +=  -Wall -Wextra -pedantic -fsigned-char       \
--funsigned-bitfields -Wno-unused-parameter -std=gnu2x -I $(INCLUDE)
-LDFLAGS	+=	-L ../lib -lmy
+-funsigned-bitfields -Wno-unused-parameter -std=gnu2x -I $(INCLUDE_DIR)
+LDFLAGS	+=	-L $(LIB_DIR) -lmy
 LD_PRELOAD	=
 
 NAME    =   asm
@@ -48,11 +52,33 @@ analyzer: CFLAGS += $(DEBUG) -fanalyzer
 analyzer: $(NAME)
 reanalyzer: fclean analyzer
 
+.PHONY: clean_tests
+clean_tests:
+	@echo [ASM] Removing criterion temporary files.
+	@rm -f *.gcda
+	@rm -f *.gcno
+
+.PHONY: tests
+tests: clean_tests
+	@if [[ "$(shell find tests/ -type f -name '*.c')" == "" ]]; then	\
+		echo "[ASM] No .c file in asm/tests/ directory - aborting.";	\
+		exit 1;															\
+	fi
+	@echo [ASM] Building tests
+	@gcc -g3 -o asm tests/*.c --coverage -lcriterion ../corewar/op.c	\
+		-I $(INCLUDE_DIR) $(LDFLAGS)
+	@echo "[ASM] Running tests :"
+	@./asm
+	@echo "[ASM] Writing line coverage log in asm/line_coverage.log."
+	@gcovr --exclude tests/ > line_coverage.log
+	@echo "[ASM] Writing branch coverage log in asm/branch_coverage.log."
+	@gcovr --exclude tests/ --branches > branch_coverage.log
+
 $(NAME): $(OBJ)
 	@echo -------------
-	@echo CC : $(CC)
-	@echo CFLAGS : $(CFLAGS)
-	@echo LDFLAGS : $(LD_PRELOAD) $(LDFLAGS)
+	@echo [ASM] CC : $(CC)
+	@echo [ASM] CFLAGS : $(CFLAGS)
+	@echo [ASM] LDFLAGS : $(LD_PRELOAD) $(LDFLAGS)
 	@gcc $(OBJ) $(LD_PRELOAD) $(LDFLAGS) -o $(NAME)
 
 %.o: %.c
@@ -63,13 +89,13 @@ $(NAME): $(OBJ)
 	fi
 
 .PHONY: clean
-clean:
-	@rm -f *.gcno
-	@rm -f *.gcda
+clean: clean_tests
+	@echo [ASM] Removing temporary and object files.
 	@rm -f vgcore.*
 	@rm -f *.log
 	@rm -f $(OBJ)
 
 .PHONY: fclean
 fclean: clean
+	@echo [ASM] Removing binary.
 	@rm -f $(NAME)
diff --git a/corewar/Makefile b/corewar/Makefile
--- a/corewar/Makefile
+++ b/corewar/Makefile
@@ -19,9 +19,11 @@ SANITIZE	=	-fsanitize=address,undefined \
 -fsanitize-recover=address,undefined
 ANALYZER	=
 
+INCLUDE_DIR	=	../include/
+LIB_DIR	=	../lib/
 CFLAGS  +=  -Wall -Wextra -pedantic -fsigned-char       \
--funsigned-bitfields -Wno-unused-parameter -std=gnu2x
-LDFLAGS	+=	-L ../lib
+-funsigned-bitfields -Wno-unused-parameter -std=gnu2x -I $(INCLUDE_DIR)
+LDFLAGS	+=	-L $(LIB_DIR) -lmy
 LD_PRELOAD	=
 
 NAME    =   corewar
@@ -33,13 +35,11 @@ re: fclean all
 
 .PHONY: debug redebug
 debug: CFLAGS += $(DEBUG)
-debug: LIB_COMPILE += debug
 debug: $(NAME)
 redebug: fclean debug
 
 .PHONY: sanitize resanitize
 sanitize: CFLAGS += $(DEBUG) $(SANITIZE)
-sanitize: LIB_COMPILE += sanitize
 sanitize: LD_PRELOAD += -lasan -lubsan
 sanitize: $(NAME)
 resanitize: fclean sanitize
@@ -47,26 +47,50 @@ resanitize: fclean sanitize
 .PHONY: analyzer reanalyzer
 analyzer: ANALYZER += on
 analyzer: CFLAGS += $(DEBUG) -fanalyzer
-analyzer: LIB_COMPILE += analyzer
 analyzer: $(NAME)
 reanalyzer: fclean analyzer
 
+.PHONY: clean_tests
+clean_tests:
+	@echo [COREWAR] Removing criterion temporary files.
+	@rm -f *.gcda
+	@rm -f *.gcno
+
+.PHONY: tests
+tests: clean_tests
+	@if [[ "$(shell find tests/ -type f -name '*.c')" == "" ]]; then		\
+		echo "[COREWAR] No .c file in corewar/tests/ directory - aborting.";\
+		exit 1;																\
+	fi
+	@echo [COREWAR] Building tests
+	@gcc -g3 -o asm tests/*.c --coverage -lcriterion ./op.c	\
+		-I $(INCLUDE_DIR) $(LDFLAGS)
+	@echo "[COREWAR] Running tests :"
+	@./corewar
+	@echo "[COREWAR] Writing line coverage log in corewar/line_coverage.log."
+	@gcovr --exclude tests/ > line_coverage.log
+	@echo -n "[COREWAR] Writing branch coverage log in "
+	@echo "corewar/branch_coverage.log."
+	@gcovr --exclude tests/ --branches > branch_coverage.log
+
+
 $(NAME): $(OBJ)
 	@echo -------------
-	@echo CC : $(CC)
-	@echo CFLAGS : $(CFLAGS)
-	@echo LDFLAGS : $(LD_PRELOAD) $(LDFLAGS)
+	@echo [COREWAR] CC : $(CC)
+	@echo [COREWAR] CFLAGS : $(CFLAGS)
+	@echo [COREWAR] LDFLAGS : $(LD_PRELOAD) $(LDFLAGS)
 	@gcc $(OBJ) $(LD_PRELOAD) $(LDFLAGS) -o $(NAME)
 
 %.o: %.c
 	@if [[ "$(ANALYZER)" != "" ]]; then\
-		$(CC) -c $(CFLAGS) $< -I ../include/ -o $@ 2>> ../analyzer.log;\
+		$(CC) -c $(CFLAGS) $< -o $@ 2>> ../analyzer.log;\
 	else\
-		$(CC) -c $(CFLAGS) $< -I ../include/ -o $@;\
+		$(CC) -c $(CFLAGS) $< -o $@;\
 	fi
 
 .PHONY: clean
 clean:
+	@echo [COREWAR] Removing temporary and object files.
 	@rm -f *.gcno
 	@rm -f *.gcda
 	@rm -f vgcore.*
@@ -75,4 +99,5 @@ clean:
 
 .PHONY: fclean
 fclean: clean
+	@echo [COREWAR] Removing binary.
 	@rm -f $(NAME)
